branches:
    only:
        - master

git:
    depth: 5
    
matrix:
    include:
    - 
        os: osx
        osx_image: xcode9.1
        before_install:
        - brew update
        - brew tap caskroom/cask
        - brew cask install powershell
        before_cache:
        - rm -f $HOME/.cache/pip/log/debug.log
        cache:
            directories:
            - $HOME/.local/share/powershell/Modules
    - 
        os: linux
        dist: trusty
        sudo: false
        addons:
            apt:
                sources:
                - 
                    sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main
                    key_url: https://packages.microsoft.com/keys/microsoft.asc
                packages:
                    - powershell
        before_cache:
        - rm -f $HOME/.cache/pip/log/debug.log
        cache:
            directories:
            - $HOME/.local/share/powershell/Modules
    fast_finish: true

install:
    - pwsh -c "iex (new-object net.webclient).downloadstring('https://get.scoop.sh')"
    - pwsh -f ".\test\bin\init.ps1"
script:
    - |
        pwsh -f ".\test\bin\test.ps1"