version: '{branch}-{build}'

branches:
    only:
        - master

build: off
deploy: off
clone_depth: 5

image:
    - Visual Studio 2017

environment:
    matrix:
        - PowerShell: 5

cache:
    - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> appveyor.yml'

matrix:
    fast_finish: true

for:
- 
    matrix:
        only:
            - PowerShell: 5
    install:
        - ps: iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
        - ps: .\test\bin\init.ps1
    test_script:
        - ps: .\test\bin\test.ps1